version: '3.8'

services:
    database:
        build:
            context: .docker/mysql
        ports:
            - 3306:3306
        restart: unless-stopped
        env_file:
            - .docker/db.env
        volumes:
            - ./_data/mysql:/var/lib/mysql

    php-fpm:
        build:
            dockerfile: .docker/php/Dockerfile
            context: .
        image: php-fpm
        restart: unless-stopped
        env_file:
            - .docker/db.env
        ports:
            - 9000
        volumes:
            - ./:/app

    nginx:
        build:
            dockerfile: .docker/nginx/Dockerfile
            context: .
        ports:
            - 80:80
        restart: unless-stopped
        volumes:
            - ./:/app
